---
- name: Check Video Stream Count
  hosts: batch.servers
  vars:
    indicator_letter: 'W'

  tasks:
    - name: Checking For Video Streams
      shell: /usr/bin/wget -O- --no-proxy -q "http://localhost/status/lighttpd?auto" |grep Scoreboard |cut -c13
      register: video_status
      failed_when: video_status.stdout == '{{ indicator_letter }}'
    - debug:
        msg: "System {{ inventory_hostname }} has ZERO active video streams '{{ video_status.stdout }}', thus OK to proceed"
      when: video_status.stdout is defined
