---

- name: Install Latest HWE Stack on Ubuntu 14.04
  hosts: '{{ hosts }}'
  user: root

  tasks:
    - name: Install linux-generic-lts-xenial package
      apt:
        name: linux-generic-lts-xenial
        state: latest
        install_recommends: yes
        update_cache: yes
        cache_valid_time: 180
      when:
        - ansible_distribution_release == 'trusty'
      register: kernel_upgrade

    - name: apt-get dist-upgrade
      command: apt-get -y dist-upgrade
      register: apt_distupgrade_output
      changed_when: "'The following packages will be upgraded' in apt_distupgrade_output.stdout"

    - name: apt-get autoremove check 
      command: apt-get -y autoremove
      register: apt_autoremove_output
      changed_when: "'The following packages will be REMOVED' in apt_autoremove_output.stdout"

    - name: reboot server
      command: reboot "Kernel Updates Triggered, reboot required!"
      async: 0
      poll: 0
      ignore_errors: true
      when:
        - ansible_distribution_release == 'trusty'
        - kernel_upgrade|changed

    - name: waiting for server to come back
      connection: local
      wait_for:
        delay: 180
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
      when:
        - ansible_distribution_release == 'trusty'
        - kernel_upgrade|changed
